name: CI Pipeline

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  checkout-build:
    runs-on: ubuntu-latest

    steps:
      # -----------------------------
      # Checkout Code
      # -----------------------------
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Verify files
        run: |
          echo "Repository successfully checked out"
          ls -R

      # -----------------------------
      # Setup Java
      # -----------------------------
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # -----------------------------
      # Build Spring Boot Jar
      # -----------------------------
      - name: Build Spring Boot Jar
        run: |
          echo "Building Spring Boot Jar..."
          mvn clean package -Dmaven.test.skip=true

      - name: Rename Artifact
        run: |
          cp target/*.jar target/backend_fb${{ github.run_number }}.jar

      # -----------------------------
      # Code Coverage Report (JaCoCo)
      # -----------------------------
      - name: Code Coverage Report (JaCoCo)
        run: |
          mvn org.jacoco:jacoco-maven-plugin:0.8.2:report

      - name: Upload JaCoCo Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco

      # -----------------------------
      # SonarCloud SAST Scan
      # -----------------------------
      - name: SonarCloud SAST Scan
        if: github.ref == 'refs/heads/main'
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=yuvraj121281_AIBootCamp-build-backend-springboot \
            -Dsonar.organization=yuvraj121281 \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN

      - name: SonarCloud Quality Gate
        if: github.ref == 'refs/heads/main'
        uses: sonarsource/sonarqube-quality-gate-action@v1
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # -----------------------------
      # OWASP Dependency Check (SCA)
      # -----------------------------
      - name: OWASP Dependency Check (SCA)
        continue-on-error: true
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/src \
            owasp/dependency-check:latest \
            --scan /src \
            --format ALL \
            --out /src/dependency-check-report \
            --disableRetiredCheck \
            --disableExperimental \
            --failOnCVSS 0

      - name: Upload SCA Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: ./dependency-check-report