name: Checkout Test

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Verify files
        run: |
          echo "Repository successfully checked out"
          echo "checkout success"
          ls -R